package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RecommendationSource identifies what produced a recommendation. The CRD shape is identical
// regardless of source, so swapping the rules engine for an LLM is a new writer, not a schema
// change.
// +kubebuilder:validation:Enum=rules;llm
type RecommendationSource string

const (
	// SourceRules means the recommendation came from kubetidy's deterministic rightsizer.
	SourceRules RecommendationSource = "rules"
	// SourceLLM means the recommendation was generated by a language model from UsageProfile
	// data. (Reserved for a future recommender; the schema already supports it.)
	SourceLLM RecommendationSource = "llm"
)

// RecommendationSpec is the request: which workload, from what source, over what inputs.
type RecommendationSpec struct {
	// TargetRef identifies the workload this recommendation applies to.
	TargetRef TargetRef `json:"targetRef"`
	// Namespace is the workload's namespace.
	Namespace string `json:"namespace"`
	// Source is what produced this recommendation (rules or llm).
	Source RecommendationSource `json:"source"`
	// GeneratedAt is when the recommendation was produced (RFC3339).
	// +optional
	GeneratedAt string `json:"generatedAt,omitempty"`
	// InputsRef names the UsageProfile (and window) the recommendation was derived from.
	// +optional
	InputsRef string `json:"inputsRef,omitempty"`
}

// ResourceChange is a proposed per-container request change.
type ResourceChange struct {
	// Container is the container name.
	Container string `json:"container"`
	// CPURequestMillicores is the proposed CPU request in millicores.
	// +optional
	CPURequestMillicores int64 `json:"cpuRequestMillicores,omitempty"`
	// MemoryRequestBytes is the proposed memory request in bytes.
	// +optional
	MemoryRequestBytes int64 `json:"memoryRequestBytes,omitempty"`
}

// RecommendationStatus is the scored, rankable result a cluster/UI consumes.
type RecommendationStatus struct {
	// Score is the 0..100 desirability of this recommendation; consumers rank by it.
	// +optional
	Score int `json:"score,omitempty"`
	// Confidence is the 0..100 confidence in the recommendation.
	// +optional
	Confidence int `json:"confidence,omitempty"`
	// MonthlySavings is the estimated $/month saved (negative means the workload should grow).
	// +optional
	MonthlySavings float64 `json:"monthlySavings,omitempty"`
	// Changes is the proposed per-container resource changes (the reversible action).
	// +optional
	Changes []ResourceChange `json:"changes,omitempty"`
	// Evidence is short human-readable justification lines.
	// +optional
	Evidence []string `json:"evidence,omitempty"`
	// Explanation is the full derivation shown to a user.
	// +optional
	Explanation string `json:"explanation,omitempty"`
	// Model records the LLM model identifier when Source is llm.
	// +optional
	Model string `json:"model,omitempty"`
	// Extensions is an open key/value area for experimental or vendor data.
	// +optional
	Extensions map[string]string `json:"extensions,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,shortName=rec
// +kubebuilder:printcolumn:name="Target",type=string,JSONPath=`.spec.targetRef.name`
// +kubebuilder:printcolumn:name="Source",type=string,JSONPath=`.spec.source`
// +kubebuilder:printcolumn:name="Score",type=integer,JSONPath=`.status.score`
// +kubebuilder:printcolumn:name="Savings/mo",type=number,JSONPath=`.status.monthlySavings`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`

// Recommendation is a single, scored, rankable rightsizing recommendation for a workload,
// produced by the rules engine today and (designed-for) an LLM in future.
type Recommendation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   RecommendationSpec   `json:"spec,omitempty"`
	Status RecommendationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RecommendationList is a list of Recommendation.
type RecommendationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Recommendation `json:"items"`
}
