// Package gitops turns rightsizing recommendations into a reviewable, reversible change set:
// one strategic-merge patch file per recommendation plus a Markdown pull-request body that
// leads with the dollar impact. It performs NO I/O of its own beyond what the caller asks
// (the caller writes the returned files); kubetidy never mutates a cluster or a repo.
//
// This is the heart of the Phase-2 "action loop": detection is commoditized, but a safe,
// auditable, dollar-quantified PR is the thing teams will actually merge.
package gitops

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/kubetidy/kubetidy/internal/model"
	"github.com/kubetidy/kubetidy/internal/patch"
)

// File is a single generated artifact: a path relative to the output directory and its
// contents.
type File struct {
	Path     string
	Contents []byte
}

// ChangeSet is the full output of a gitops export: the per-recommendation patch files plus a
// human-facing PR body, with the aggregate dollar impact precomputed.
type ChangeSet struct {
	Files             []File
	PRBody            string
	PRTitle           string
	TotalMonthlySaved float64
	Count             int
}

// Options tunes the export.
type Options struct {
	// PatchDir is the directory (relative path used in file paths and the PR body) that the
	// generated patch files live under. Defaults to "kubetidy-patches".
	PatchDir string
	// TopN limits how many recommendations are included (0 = all). Recommendations are taken
	// in descending order of monthly savings.
	TopN int
	// IncludeGrow, when false (default), excludes "grow" recommendations (negative savings)
	// from the change set, since a GitOps cost-reduction PR usually wants only reductions.
	IncludeGrow bool
}

// Build assembles a ChangeSet from a scan result. It is pure: it returns the files to write
// and the PR text, but writes nothing itself.
func Build(result model.ScanResult, opts Options) (ChangeSet, error) {
	dir := opts.PatchDir
	if dir == "" {
		dir = "kubetidy-patches"
	}

	recs := selectRecommendations(result.Recommendations, opts)

	cs := ChangeSet{Count: len(recs)}
	for _, rec := range recs {
		p, err := patch.StrategicMergePatch(rec)
		if err != nil {
			return ChangeSet{}, fmt.Errorf("gitops: building patch for %s: %w", rec.Workload.Ref(), err)
		}
		cs.Files = append(cs.Files, File{
			Path:     filepath.Join(dir, patchFileName(rec)),
			Contents: append(p, '\n'),
		})
		if rec.MonthlySavings > 0 {
			cs.TotalMonthlySaved += rec.MonthlySavings
		}
	}

	cs.PRTitle = prTitle(cs.TotalMonthlySaved, len(recs))
	cs.PRBody = prBody(result, recs, dir, cs.TotalMonthlySaved)
	return cs, nil
}

// selectRecommendations filters and ranks recommendations per the options.
func selectRecommendations(recs []model.Recommendation, opts Options) []model.Recommendation {
	out := make([]model.Recommendation, 0, len(recs))
	for _, r := range recs {
		if !opts.IncludeGrow && r.MonthlySavings < 0 {
			continue
		}
		out = append(out, r)
	}
	sort.SliceStable(out, func(i, j int) bool {
		return out[i].MonthlySavings > out[j].MonthlySavings
	})
	if opts.TopN > 0 && opts.TopN < len(out) {
		out = out[:opts.TopN]
	}
	return out
}

// patchFileName returns a filesystem-safe, deterministic name for a recommendation's patch,
// e.g. "deployment-shop-checkout-api.json".
func patchFileName(rec model.Recommendation) string {
	kind := strings.ToLower(string(rec.Workload.Kind))
	parts := []string{kind, rec.Workload.Namespace, rec.Workload.Name}
	if rec.ContainerName != "" && rec.ContainerName != rec.Workload.Name {
		parts = append(parts, rec.ContainerName)
	}
	name := strings.Join(filterEmpty(parts), "-")
	return sanitize(name) + ".json"
}

// prTitle builds the PR title, leading with the dollar impact (the thing reviewers care
// about), e.g. "Rightsize 12 workloads — save ~$7,420/month".
func prTitle(totalSaved float64, n int) string {
	noun := "workload"
	if n != 1 {
		noun += "s"
	}
	return fmt.Sprintf("Rightsize %d %s — save ~%s/month", n, noun, dollars(totalSaved))
}

// prBody renders the Markdown PR description: a summary, a per-recommendation table with the
// dollar delta and evidence, and clear "how to apply / how to revert" instructions.
func prBody(result model.ScanResult, recs []model.Recommendation, dir string, totalSaved float64) string {
	var b strings.Builder

	b.WriteString("## kubetidy rightsizing\n\n")
	fmt.Fprintf(&b, "Generated by [kubetidy](https://github.com/mayur-tolexo/kubetidy) from a read-only scan of `%s`.\n\n", contextOr(result.Context))
	fmt.Fprintf(&b, "**Estimated savings: ~%s/month** across %d workload(s).\n\n", dollars(totalSaved), len(recs))

	if result.Tier == model.TierSnapshot {
		b.WriteString("> ⚠️ These numbers come from a single metrics-server snapshot (Tier 0), not historical peaks. ")
		b.WriteString("Review carefully and prefer a Prometheus-backed scan (`--prometheus-url`) before merging.\n\n")
	}

	b.WriteString("| Workload | Container | CPU | Memory | Savings | Confidence |\n")
	b.WriteString("|---|---|---|---|---|---|\n")
	for _, rec := range recs {
		fmt.Fprintf(&b, "| `%s` | `%s` | %s | %s | %s | %d%% |\n",
			rec.Workload.Ref(),
			rec.ContainerName,
			cpuChange(rec),
			memChange(rec),
			savingsLabel(rec),
			rec.Confidence.Percent(),
		)
	}
	b.WriteString("\n")

	b.WriteString("## How to apply\n\n")
	fmt.Fprintf(&b, "Each change is an isolated strategic-merge patch under `%s/`. Apply all:\n\n", dir)
	b.WriteString("```sh\n")
	fmt.Fprintf(&b, "for f in %s/*.json; do\n", dir)
	b.WriteString("  kubectl patch -f \"$f\" --type=strategic --patch-file \"$f\"\n")
	b.WriteString("done\n")
	b.WriteString("```\n\n")
	b.WriteString("Or merge this PR if these files are tracked by your GitOps controller (Argo CD / Flux).\n\n")

	b.WriteString("## How to revert\n\n")
	b.WriteString("Every change only adjusts resource requests/limits and is fully reversible: revert this commit, ")
	b.WriteString("or re-apply your previous values. kubetidy never deletes workloads or mutates anything else.\n")

	return b.String()
}

// --- small helpers (formatting) ---

func cpuChange(rec model.Recommendation) string {
	return fmt.Sprintf("%dm → %dm", rec.Current.Requests.CPUMillicores, rec.Proposed.Requests.CPUMillicores)
}

func memChange(rec model.Recommendation) string {
	return fmt.Sprintf("%s → %s", mem(rec.Current.Requests.MemoryBytes), mem(rec.Proposed.Requests.MemoryBytes))
}

// mem humanizes a byte count adaptively (Mi below 1Gi, Gi above), never "0.0Gi".
func mem(bytes int64) string {
	const (
		mi = 1024 * 1024
		gi = 1024 * mi
	)
	switch {
	case bytes <= 0:
		return "0"
	case bytes < gi:
		return fmt.Sprintf("%dMi", (bytes+mi-1)/mi)
	default:
		return fmt.Sprintf("%.1fGi", float64(bytes)/float64(gi))
	}
}

// savingsLabel renders the savings cell: a positive value as "$210/mo", a negative (grow) as
// "+$7/mo (grow)".
func savingsLabel(rec model.Recommendation) string {
	if rec.MonthlySavings < 0 {
		return fmt.Sprintf("+%s/mo (grow)", dollars(-rec.MonthlySavings))
	}
	return fmt.Sprintf("%s/mo", dollars(rec.MonthlySavings))
}

// dollars renders a rounded, thousands-separated dollar amount, e.g. "$7,420".
func dollars(v float64) string {
	n := int64(v + 0.5)
	if v < 0 {
		n = -int64(-v + 0.5)
	}
	neg := n < 0
	if neg {
		n = -n
	}
	s := fmt.Sprintf("%d", n)
	var parts []string
	for len(s) > 3 {
		parts = append([]string{s[len(s)-3:]}, parts...)
		s = s[:len(s)-3]
	}
	parts = append([]string{s}, parts...)
	out := "$" + strings.Join(parts, ",")
	if neg {
		out = "-" + out
	}
	return out
}

func contextOr(ctx string) string {
	if ctx == "" {
		return "(current context)"
	}
	return ctx
}

func filterEmpty(in []string) []string {
	out := in[:0]
	for _, s := range in {
		if s != "" {
			out = append(out, s)
		}
	}
	return out
}

// sanitize replaces any character that is not a-z, 0-9, '-' or '.' with '-' so the result is
// a safe file name.
func sanitize(s string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(s) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '-', r == '.':
			b.WriteRune(r)
		default:
			b.WriteRune('-')
		}
	}
	return b.String()
}
